# Generated by Django 4.2.3 on 2023-09-01 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_proyecto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='contraseña',
            field=models.CharField(default=0, max_length=20, verbose_name='Contraseña'),
            preserve_default=False,
        ),
    ]
