# Generated by Django 4.2.3 on 2023-09-02 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_proyecto', '0002_estudiante_contraseña'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='carnet',
            field=models.CharField(default=2023055, max_length=20, unique=True, verbose_name='Carnet'),
            preserve_default=False,
        ),
    ]
