# Generated by Django 4.2.3 on 2023-09-22 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_fecha_de_publicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='autor',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
